[project]
name = "ade-book-keep"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "0xtin", email = "caugust19.ac@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ade-book-keep = "ade_book_keep:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = "."

[tool.hatch.build.targets.wheel]
packages = ["ade_book_keep"]